groups:
- name: alertmanager.rules
  rules:
  #1 Прверка на правильность применения конфигурации Alertmanager.
  - alert: AlertmanagerFailedReload
    expr: max_over_time(alertmanager_config_last_reload_successful[5m]) == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      description: Перезагрузка конфигурации Alertmanager не удалась {{ $labels.namespace }}/{{$labels.exported_instance}}.
      summary: Невозможность перезагрузить конфигурацию Alertmanager.
  #2 Прверка на ошибки отправки оповещений  Alertmanager.
  - alert: AlertmanagerFailedToSendAlerts
    expr: rate(alertmanager_notifications_failed_total{integration="telegram"}[5m]) > 0.01
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Alertmanager {{ $labels.exported_instance}} не отправил уведомления {{ $value }}  в интеграцию {{ $labels.integration }}.
      summary: Alertmanager не может направить оповещение в соответствующую интеграцию.

