groups:
- name: CoreDNS
  rules:
  #1 Проверка доступности сервиса CoreDNS
    - alert: CoreDNSDown
      expr: absent(up{job="kube-dns"} == 1)
      for: 15m
      labels:
        severity: critical
      annotations:
        description: "CoreDNS кластер {{ $labels.datacenter }} / {{ $labels.exported_instance }} : недоступен в течении 15 минут"
        summary: CoreDNS has disappeared  target discovery.
  #2 Сервис CoreDNS возвращает слишком много ошибок (больше 3%)
    - alert: CoreDNSErrorsHigh
      expr: sum without (pod, instance, server, zone, view, rcode, plugin) (rate(coredns_dns_responses_total{job="kube-dns",rcode="SERVFAIL"}[5m])) / sum without (pod, instance, server, zone, view, rcode, plugin) (rate(coredns_dns_responses_total{job="kube-dns"}[5m])) > 0.03
      for: 10m
      labels:
        severity: critical
      annotations:
        description: CoreDNS  {{ $labels.datacenter }} is returning SERVFAIL for {{ $value | humanizePercentage }} of requests.
        summary: CoreDNS is returning SERVFAIL.
  #3 Слишком медленные запросы CoreDNS
    - alert: CoreDNSLatencyHigh
      expr:   histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job="kube-dns"}[5m])) by(server, zone, le)) > 4
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "CoreDNS has 99th percentile latency of {{ $value }} seconds for server     {{ $labels.datacenter }} ."
        summary: Слишком медленные запросы CoreDNS

  #4 Медленное перенапровление запросов DNS 
    - alert: CoreDNSForwardLatencyHigh
      expr: histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{job="kube-dns"}[5m])) by(to, le)) > 4
      for: 10m
      labels:
        severity: warning
      annotations:
        description: "CoreDNS has 99th percentile latency of {{ $value }} seconds forwarding requests to {{ $labels.to }}."
        summary: Медленное перенапровление запросов DNS

  #5 Много ошибок при перенаправлении DNS запросов 3%
    - alert: CoreDNSForwardErrorsHigh
      expr: sum(rate(coredns_forward_responses_total{job="kube-dns",rcode="SERVFAIL"}[5m])) / sum(rate(coredns_forward_responses_total{job="kube-dns"}[5m])) > 0.03
      for: 10m
      labels:
        severity: critical
      annotations:
        description: " CoreDNS is returning SERVFAIL for {{ $value | humanizePercentage }} of forward requests to {{ $labels.to }}"
        summary: Много ошибок при перенаправлении DNS запросов

  #6 Проверка работоспособности CoreDNS (Healthcheck) по серверам
    - alert: CoreDNSForwardHealthcheckFailureCount
      expr: sum(rate(coredns_forward_healthcheck_failures_total{job="kube-dns"}[5m])) by (to) > 0
      for: 10m
      labels:
        severity: warning
      annotations:
        description: "CoreDNS health checks have failed to upstream server {{ $labels.to }}."
        summary: Не удалось выполнить проверку работоспособности  (Healthcheck) CoreDNS

  #7 Количество паник CoreDNS
    - alert: CorednsPanicCount
      expr: increase(coredns_panics_total[1m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        description: "Number of CoreDNS panics encountered\n  VALUE = {{ $value }}\n   datacenter {{ $labels.datacenter }} / {{ $labels.exported_instance }} "
        summary: CoreDNS Panic Count 
