groups:
- name: Elastic_rules
  rules:
  #1. elasticsearch_cluster_health_up - 1 - если кластер в порядке, 0 - если нет
  - alert: ElasticsearchClusterHealthUp
    expr: elasticsearch_cluster_health_up  == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Elasticsearch cluster health (Claster {{ $labels.app }})
      description: "Elasticsearch cluster health \n ip_instance = {{ $labels.exported_instance }} , \n pod_name = {{ $labels.pod_name }}, \n workernode = {{ $labels.pod_name }}"

  #2. Elastic Cluster Red status
  - alert: ElasticsearchClusterRed
    expr: elasticsearch_cluster_health_status{color="red"} == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Elasticsearch Cluster Red (instance {{ $labels.app }})
      description: "Elastic Cluster Red status \n ip_instance = {{ $labels.exported_instance }} , \n pod_name = {{ $labels.pod_name }}, \n workernode = {{ $labels.pod_name }}"

  #3. The heap usage is over 90% 
  - alert: ElasticsearchHeapUsageTooHigh
    expr: (elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}) * 100 > 90
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: Elasticsearch Heap Usage Too High (instance {{ $labels.app }})
      description: "The heap usage is over 90% \n  VALUE = {{ $value }},\n ip_instance = {{ $labels.exported_instance }} , \n pod_name = {{ $labels.pod_name }}, \n workernode = {{ $labels.pod_name }}"

  #4. The heap usage is over 80%
  - alert: ElasticsearchHeapUsageWarning
    expr: (elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}) * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Elasticsearch Heap Usage warning (instance {{ $labels.app }})
      description: "The heap usage is over 80% \n  VALUE = {{ $value }},\n ip_instance = {{ $labels.exported_instance }} , \n pod_name = {{ $labels.pod_name }}, \n workernode = {{ $labels.pod_name }}"

  #5. Elasticsearch has unassigned shards
  - alert: ElasticsearchUnassignedShards
    expr: elasticsearch_cluster_health_unassigned_shards > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Elasticsearch unassigned shards (instance {{ $labels.app }})
      description: "Elasticsearch has unassigned shards \n  VALUE = {{ $value }},\n ip_instance = {{ $labels.exported_instance }} , \n pod_name = {{ $labels.pod_name }}, \n workernode = {{ $labels.pod_name }}"
  #6. No new documents for 10 min!
        #- alert: ElasticsearchNoNewDocuments
        #  expr: increase(elasticsearch_indices_indexing_index_total{es_data_node="true"}[60m]) < 1
        #  for: 10m
        #  labels:
        #    severity: warning
        #  annotations:
        #    summary: Elasticsearch no new documents (instance {{ $labels.instance }})
        #    description: "No new documents for 10 min!\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  #7. Missing node in Elasticsearch cluster
  - alert: ElasticsearchHealthyNodesLow
    expr: rate(sum(elasticsearch_cluster_health_number_of_nodes) by(namespace)[15m])!=0
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: Elasticsearch Healthy Nodes (instance {{ $labels.app }})
      description: "Missing node in Elasticsearch cluster \n  VALUE = {{ $value }},\n ip_instance = {{ $labels.namespace }}"

 
