groups:
- name: etcd
  rules:
  #1 Прверка на четность количества членов кластера ETCD и одновременно проверка здоровья кластера, достаточность для кворума кластера.
    - alert: etcdInsufficientMembers
      expr: sum(up{job=~"ETCD"} == bool 1) without (instance) < ((count(up{job=~"ETCD"}) without (instance) + 1) / 2)
      for: 0m
      labels:
        severity: critical
      annotations:
        description: "etcd кластер {{ $labels.datacenter }} / {{ $labels.exported_instance }} : имеет недостаточно членов ({{ $value }}"
        summary: etcd cluster has insufficient number of members.
  #2 Прверка на наличие лидера  кластера ETCD
    - alert: etcdNoLeader
      expr: etcd_server_has_leader == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        description: >-
          etcd кластер "{{ $labels.job }}": члены: {{ $labels.exported_instance }} не имеет лидера.
        summary: etcd кластер не имеет лидера.
  #3 Кластер Etcd обнаружил более 2 изменений лидера в последние 10 минут (частые выборы лидера)
    - alert: etcdHighNumberOfLeaderChanges
      expr: increase(etcd_server_leader_changes_seen_total[10m]) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "etcd кластер {{ $labels.job }}: обнаружил {{ $value }} выборов за 10 минут"
        summary: etcd кластер частые выборы лидера

  #4 Общение между членами кластера и т. д. происходит медленно
    - alert: etcdMemberCommunicationSlow
      expr: histogram_quantile(0.99,rate(etcd_network_peer_round_trip_time_seconds_bucket[5m])) > 0.2
      for: 10m
      labels:
        severity: warning
      annotations:
        description: "etcd cluster {{ $labels.job }}: member communication with {{ $labels.To }} is taking {{ $value }}s on etcd instance {{ $labels.exported_instance }}."
        summary: etcd cluster member communication is slow.
  #5 кластер etcd имеет большое количество сбоев предложений
    - alert: etcdHighNumberOfFailedProposals
      expr: rate(etcd_server_proposals_failed_total[15m]) > 5
      for: 15m
      labels:
        severity: warning
      annotations:
        description: " etcd cluster {{ $labels.job }}: {{ $value }} proposal failures within the last 15 minutes on etcd instance {{ $labels.exported_instance }}."
        summary: кластер etcd имеет большое количество сбоев предложений.
  #6 кластер 99-го процентиля длительности fsync слишком высок
    - alert: etcdHighFsyncDurations
      expr: histogram_quantile(0.99,rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) > 1
      for: 10m
      labels:
        severity: critical
      annotations:
        description: "etcd cluster {{ $labels.job }}: 99th percentile fsync durations are {{ $value }}s on etcd instance {{ $labels.exported_instance }}."
        summary: кластер 99-го процентиля длительности fsync слишком высоки.
  #7 размер базы данных превышает определенную квоту на экземпляр
    - alert: etcdDatabaseQuotaLowSpace
      expr: (last_over_time(etcd_mvcc_db_total_size_in_bytes[5m]) / last_over_time(etcd_server_quota_backend_bytes[5m]))*100 > 95
      for: 10m
      labels:
        severity: critical
      annotations:
        description: " кластер etcd {{ $labels.job }}: размер базы данных превышает определенную квоту на экземпляре {{ $labels.exported_instance }}, пожалуйста, дефрагментируйте или увеличьте квоту или база будет отключена, когда она будет заполнена."
        summary: размер базы данных превышает определенную квоту на экземпляр.
