groups:
- name: general.rules
  rules:
#1 Это предупреждение, предназначенное для обеспечения работоспособности всего конвейера
  - alert: Watchdog
    annotations:
      description: This is an alert meant to ensure that the entire alerting pipeline is functional.
      summary: An alert that should always be firing to certify that Alertmanager is working properly.
    expr: vector(1)
    labels:
      severity: info
#2 Этот алерт проверяет доступность Targets и срабатывет при падении любого.
  - alert: TargetDown
    annotations:
      description: "{{ $value }}% of the {{ $labels.job }}/{{$labels.service }} targets in {{ $labels.namespace }} namespace are down."
      summary: Один или несколько targets недоступен.
    expr: 100 * (count(up == 0) BY (datacenter,job, namespace, service) / count(up) BY (datacenter,job, namespace, service)) > 10
    for: 10m
    labels:
      severity: warning
#3 Этот алерт должен попадать в ресивер NULL и сконфигурирован и запрещать алерты с уровнем Info
  - alert: InfoInhibitor
    annotations:
      description:  Этот алерт должен попадать в ресивер NULL и сконфигурирован и запрещать алерты с уровнем Info
      summary: Info-level alert inhibition.
    expr: ALERTS{severity = "info"} == 1 unless on(namespace) ALERTS{alertname!= "InfoInhibitor", severity =~ "warning|critical", alertstate="firing"} == 1
    labels:
      severity: info
#4 Правило по тротлингу по CPU для подов
  - alert: CPUThrottlingHigh
    expr: sum by (container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{container!=""}[5m])) / sum by (container, pod, namespace) (increase(container_cpu_cfs_periods_total[5m])) > (25 / 100)
    for: 15m
    labels:
      severity: info
    annotations:
      description: throttling of CPU in namespace {{ $labels.namespace }} for container {{ $labels.container }} in pod {{ $labels.pod }}.
      summary: Processes experience elevated CPU throttling.


