groups:
- name: kubernetes-system.rules
  rules:
  #1 Различные семантические версии запущенных компонентов Kubernetes.
  - alert: KubeVersionMismatch
    expr: count by (cluster) (count by (git_version, cluster) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"}, "git_version", "$1", "git_version", "(v[0-9]*.[0-9]*).*"))) > 1
    for: 15m
    labels:
      severity: warning
    annotations:
      description: There are {{ $value }} different semantic versions of Kubernetes components running.
      summary: Different semantic versions of Kubernetes components running.
  #2 За последние 15 минут клиент сервера Kubernetes API испытывает частоту ошибок более 1%.
  - alert: KubeClientErrors
    expr: (sum by (cluster, instance, job, namespace) (rate(rest_client_requests_total{code=~"5.."}[5m])) / sum by (cluster, instance, job, namespace) (rate(rest_client_requests_total[5m]))) > 0.01
    for: 15m
    labels:
      severity: warning
    annotations:
      description: Kubernetes API server client '{{ $labels.job }}/{{ $labels.instance }}' is experiencing {{ $value | humanizePercentage }} errors.'
      summary: Kubernetes API server client is experiencing errors.