groups:
- name: kube-apiserver.rules
  rules:
  #1 Клиентский сертификат, используемый для аутентификации у apiserver, истекает менее чем за 7 дней       
  - alert: KubeClientCertificateExpiration
    expr: apiserver_client_certificate_expiration_seconds_count{job="kubernetes-apiservers"} > 0 and histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="kubernetes-apiservers"}[5m]))) < 604800
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Клиентский сертификат, используемый для аутентификации у apiserver {{ $labels.datacenter }} / {{ $labels.exported_instance }}, истекает менее чем за 7 дней
      summary: Клиентский сертификат, используемый apiserver, истекает.

  #2 Клиентский сертификат, используемый для аутентификации у apiserver, истекает менее чем за 24 часа  
  - alert: KubeClientCertificateExpiration
    expr: apiserver_client_certificate_expiration_seconds_count{job="kubernetes-apiservers"} > 0 and histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="kubernetes-apiservers"}[5m]))) < 86400
    for: 5m
    labels:
      severity: critical
    annotations:
      description: Клиентский сертификат, используемый для аутентификации у apiserver {{ $labels.datacenter }} / {{ $labels.exported_instance }}, истекает менее чем за 24 часа .
      summary: Клиентский сертификат, используемый apiserver, истекает.

  #3 API Kubernetes сообщил об ошибках. Он оказался недоступным более 4 раз, усредненных за последние 10 минут
  - alert: KubeAggregatedAPIErrors
    expr: sum by (name, namespace, cluster) (increase(aggregator_unavailable_apiservice_total[10m])) > 4
    labels:
      severity: warning
    annotations:
      description: Kubernetes  API {{ $labels.name }}/{{ $labels.namespace }} сообщил об ошибках. Он оказался недоступным {{ $value | humanize }} усредненных за последние 10 минут.
      summary: Kubernetes API сообщил об ошибках.
  #4 Это критическое предупреждение. API Kubernetes не отвечает.
  - alert: KubeAPIDown
    expr: absent(up{job="kubernetes-apiservers"} == 1)
    for: 15m
    labels:
      severity: critical
    annotations:
      description: API Kubernetes не отвечает {{ $labels.datacenter }} / {{ $labels.exported_instance }}
      summary: API Kubernetes не отвечает.
  #5 Клиент не сможет взаимодействовать с кластером. Apiserver прекратил более 20% входящих запросов
  - alert: KubeAPITerminatedRequests
    expr: sum(rate(apiserver_request_terminations_total{job="kubernetes-apiservers"}[10m])) / (sum(rate(apiserver_request_total{job="kubernetes-apiservers"}[10m])) + sum(rate(apiserver_request_terminations_total{job="kubernetes-apiservers"}[10m]))) > 0.2
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Kubernetes apiserver прекратил  {{ $value | humanizePercentage }} входящих запросов.
      summary: Kubernetes apiserver прекратил  {{ $value | humanizePercentage }} входящих запросов.
