groups:
- name: kubernetes-storage.rules
  rules:
  #1 Мониторинг емкости PersistentVolume осталось меньше 7%
  - alert: KubePersistentVolumeFillingUp
    expr: (kubelet_volume_stats_available_bytes{job="kubernetes-nodes-kubelet",namespace=~".*"} / kubelet_volume_stats_capacity_bytes{job="kubernetes-nodes-kubelet",namespace=~".*"}) < 0.03 and kubelet_volume_stats_used_bytes{job="kubernetes-nodes-kubelet",namespace=~".*"} > 0 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_access_mode{access_mode="ReadOnlyMany"} == 1 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
    for: 1m
    labels:
      severity: critical
    annotations:
      description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ $value | humanizePercentage }} free.
      summary: PersistentVolume is filling up.
  #2 Мониторинг емкости PersistentVolume осталось меньше 15%
  - alert: KubePersistentVolumeFillingUp
    expr: (kubelet_volume_stats_available_bytes{job="kubernetes-nodes-kubelet",namespace=~".*"} / kubelet_volume_stats_capacity_bytes{job="kubernetes-nodes-kubelet",namespace=~".*"}) < 0.15 and kubelet_volume_stats_used_bytes{job="kubernetes-nodes-kubelet",namespace=~".*"} > 0 and predict_linear(kubelet_volume_stats_available_bytes{job="kubernetes-nodes-kubelet",namespace=~".*"}[6h], 4 * 24 * 3600) < 0 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_access_mode{access_mode="ReadOnlyMany"} == 1 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
    for: 1h
    labels:
      severity: warning
    annotations:
      description: Based on recent sampling,  {{ $labels.datacenter }}/{{ $labels.exporter_instance }} the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to fill up within four days. Currently {{ $value | humanizePercentage }} is available.
      summary: PersistentVolume is filling up.
  #3 Мониторинг емкости inodes на PersistentVolume осталось меньше 7%
  - alert: KubePersistentVolumeInodesFillingUp
    expr: (kubelet_volume_stats_inodes_free{job="kubernetes-nodes-kubelet",namespace=~".*"} / kubelet_volume_stats_inodes{job="kubernetes-nodes-kubelet",namespace=~".*"}) < 0.03 and kubelet_volume_stats_inodes_used{job="kubernetes-nodes-kubelet",namespace=~".*"} > 0 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_access_mode{access_mode="ReadOnlyMany"} == 1 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
    for: 1m
    labels:
      severity: critical
    annotations:
      description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} only has {{ $value | humanizePercentage }} free inodes.
      summary: PersistentVolumeInodes are filling up.
  #4 Мониторинг емкости inodes на PersistentVolume осталось меньше 15%
  - alert: KubePersistentVolumeInodesFillingUp
    expr: (kubelet_volume_stats_inodes_free{job="kubernetes-nodes-kubelet",namespace=~".*"} / kubelet_volume_stats_inodes{job="kubernetes-nodes-kubelet",namespace=~".*"}) < 0.15 and kubelet_volume_stats_inodes_used{job="kubernetes-nodes-kubelet",namespace=~".*"} > 0 and predict_linear(kubelet_volume_stats_inodes_free{job="kubernetes-nodes-kubelet",namespace=~".*"}[6h], 4 * 24 * 3600) < 0 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_access_mode{access_mode="ReadOnlyMany"} == 1 unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
    for: 1h
    labels:
      severity: warning
    annotations:
      description: Based on recent sampling, the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is expected to run out of inodes within four days. Currently {{ $value | humanizePercentage }} of its inodes are free.
      summary: PersistentVolumeInodes are filling up.
  #5 Мониторинг ошибок записи на PersistentVolume
  - alert: KubePersistentVolumeErrors
    expr: kube_persistentvolume_status_phase{job="kube-state-metrics",phase=~"Failed|Pending"} > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: The persistent volume {{ $labels.persistentvolume }} has status {{ $labels.phase }}.
      summary: PersistentVolume is having issues with provisioning  