groups:
- name: kubernetes-system-kubelet.rules
  rules:
  #1 15 мин не готов узел (node) Kubernetes (статус = "not ready")
  - alert: KubeNodeNotReady
    expr: kube_node_status_condition{condition="Ready",job="kube-state-metrics",status="true"} == 0
    for: 15m
    labels:
      severity: warning
    annotations:
      description: has been unready  '{{ $labels.node }}' for more than 15 minutes.
      summary: Node is not ready.
  #2 Статус ноды не отвечает (unreachable)
  - alert: KubeNodeUnreachable
    expr: (kube_node_spec_taint{effect="NoSchedule",job="kube-state-metrics",key="node.kubernetes.io/unreachable"} unless ignoring (key, value) kube_node_spec_taint{job="kube-state-metrics",key=~"ToBeDeletedByClusterAutoscaler|cloud.google.com/impending-node-termination|aws-node-termination-handler/spot-itn"}) == 1
    for: 15m
    labels:
      severity: warning
    annotations:
      description:  "{{ $labels.node }} is unreachable and some workloads may be rescheduled."
      summary: Node is unreachable.
  #3 Состояние готовности узла менялось несколько раз за последние 15 минут.(больше 2-х раз за 15 минут)
  - alert: KubeNodeReadinessFlapping
    expr: sum by (cluster, node) (changes(kube_node_status_condition{condition="Ready",status="true"}[15m])) > 2
    for: 15m
    labels:
      severity: warning
    annotations:
      description: The readiness status of node {{ $labels.node }} has changed {{ $value }} times in the last 15 minutes.
      summary: Node readiness status is flapping.
  #4 Клиентский сертификат, используемый для аутентификации у Kubelet, истекает менее чем за 7 дней 
  - alert: KubeletClientCertificateExpiration
    expr: kubelet_certificate_manager_client_ttl_seconds < 604800
    labels:
      severity: warning
    annotations:
      description: Client certificate for Kubelet on node {{ $labels.node }} expires in {{ $value | humanizeDuration }}.
      summary: Kubelet client certificate is about to expire.
  #5 Клиентский сертификат, используемый для аутентификации у Kubelet, истекает менее чем за 24 часа
  - alert: KubeletClientCertificateExpiration
    expr: kubelet_certificate_manager_client_ttl_seconds < 86400
    labels:
      severity: critical
    annotations:
      description: Client certificate for Kubelet on node {{ $labels.node }} expires in {{ $value | humanizeDuration }}.
      summary: Kubelet client certificate is about to expire.
  #7 Серверный сертификат, используемый для аутентификации у Kubelet, истекает менее чем за 7 дней
  - alert: KubeletServerCertificateExpiration
    expr: kubelet_certificate_manager_server_ttl_seconds < 604800
    labels:
      severity: warning
    annotations:
      description: Server certificate for Kubelet on node {{ $labels.node }} expires in {{ $value | humanizeDuration }}.
      summary: Kubelet server certificate is about to expire.
  #7 Серверный сертификат, используемый для аутентификации у Kubelet, истекает менее чем за 24 часа
  - alert: KubeletServerCertificateExpiration
    expr: kubelet_certificate_manager_server_ttl_seconds < 86400
    labels:
      severity: critical
    annotations:
      description: Server certificate for Kubelet on node {{ $labels.node }} expires in {{ $value | humanizeDuration }}.
      summary: Kubelet server certificate is about to expire.
  #8 Kubelet на узле не смог обновить свой клиентский сертификат (ошибки XX за последние 15 минут)
  - alert: KubeletClientCertificateRenewalErrors
    expr: increase(kubelet_certificate_manager_client_expiration_renew_errors[5m]) > 0
    for: 15m
    labels:
      severity: warning
    annotations:
      description: Kubelet on node {{ $labels.node }} has failed to renew its client certificate ({{ $value | humanize }} errors in the last 5 minutes).
      summary: Kubelet has failed to renew its client certificate.
  #9 Kubelet на узле не смог обновить свой сертификат сервера (ошибки XX за последние 5 минут)
  - alert: KubeletServerCertificateRenewalErrors
    expr: increase(kubelet_server_expiration_renew_errors[5m]) > 0
    for: 15m
    labels:
      severity: warning
    annotations:
      description: Kubelet on node {{ $labels.node }} has failed to renew its server certificate ({{ $value | humanize }} errors in the last 5 minutes).
      summary: Kubelet has failed to renew its server certificate.
  #10 Сервис  Kubelet не отвечает
  - alert: KubeletDown
    expr: absent(up{job="kubernetes-nodes-kubelet"} == 1)
    for: 15m
    labels:
      severity: critical
    annotations:
      description: the monitoring system has not been able to reach any of the cluster’s Kubelets for more than 15 minutes.
      summary: Target disappeared from Victoria_Metrics target discovery.