groups:
- name: node-exporter.rules
  rules:
  #1 Проверка на остаток места на файловой системе ноды плюс прогнозирование окончания места в 24 часа
  - alert: NodeFilesystemSpaceFillingUp
    expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 15 and predict_linear(node_filesystem_avail_bytes{fstype!="",job="node-exporter"}[6h], 24 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 1h
    labels:
      severity: warning
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up.
      summary: Filesystem is predicted to run out of space within the next 24 hours.
  #2 Проверка на остаток места на файловой системе ноды плюс прогнозирование окончания места в 4 часа
  - alert: NodeFilesystemSpaceFillingUp
    expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 10 and predict_linear(node_filesystem_avail_bytes{fstype!="",job="node-exporter"}[6h], 4 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up fast.
      summary: Filesystem is predicted to run out of space within the next 4 hours.
  #3 Проверка на остаток места на файловой системе ноды осталось 5%
  - alert: NodeFilesystemAlmostOutOfSpace
    expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 5 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 30m
    labels:
      severity: warning
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.
      summary: Filesystem has less than 5% space left.
  #4 Проверка на остаток места на файловой системе ноды осталось 3%
  - alert: NodeFilesystemAlmostOutOfSpace
    expr: (node_filesystem_avail_bytes{fstype!="",job="node-exporter"} / node_filesystem_size_bytes{fstype!="",job="node-exporter"} * 100 < 3 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 30m
    labels:
      severity: critical
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.
      summary: Filesystem has less than 3% space left.
  #5 Проверка на остаток количество инодов  файловой системе ноды плюс прогнозирование окончания инодов в 24 часа
  - alert: NodeFilesystemFilesFillingUp
    expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 40 and predict_linear(node_filesystem_files_free{fstype!="",job="node-exporter"}[6h], 24 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 1h
    labels:
      severity: warning
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up.
      summary: Filesystem is predicted to run out of inodes within the next 24 hours.
  #6 Проверка на остаток количество инодов  файловой системе ноды плюс прогнозирование окончания инодов в 4 часа
  - alert: NodeFilesystemFilesFillingUp
    expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 20 and predict_linear(node_filesystem_files_free{fstype!="",job="node-exporter"}[6h], 4 * 60 * 60) < 0 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left and is filling up fast.
      summary: Filesystem is predicted to run out of inodes within the next 4 hours.
  #7 Проверка на остаток количество инодов  файловой системе ноды осталось 5%
  - alert: NodeFilesystemAlmostOutOfFiles
    expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 5 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 1h
    labels:
      severity: warning
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.
      summary: Filesystem has less than 5% inodes left.
  #8 Проверка на остаток количество инодов  файловой системе ноды осталось 3%
  - alert: NodeFilesystemAlmostOutOfFiles
    expr: (node_filesystem_files_free{fstype!="",job="node-exporter"} / node_filesystem_files{fstype!="",job="node-exporter"} * 100 < 3 and node_filesystem_readonly{fstype!="",job="node-exporter"} == 0)
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available inodes left.
      summary: Filesystem has less than 3% inodes left.
  #9 Сетевой интерфейс сообщает о многих ошибках получения.
  - alert: NodeNetworkReceiveErrs
    expr: rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
    for: 1h
    labels:
      severity: warning
    annotations:
      description:  interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} receive errors in the last two minutes {{ $labels.instance }}
      summary: Network interface is reporting many receive errors.
  #10 Сетевой интерфейс сообщает о многих исходящих ошибках . 
  - alert: NodeNetworkTransmitErrs
    expr: rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01
    for: 1h
    labels:
      severity: warning
    annotations:
      description: interface {{ $labels.device }} has encountered {{ printf "%.0f" $value }} transmit errors in the last two minutes.
      summary: Network interface is reporting many transmit errors.
  #11 Количество коннтреков приближается к пределу (отслеживание количества соединений) 75%
  - alert: NodeHighNumberConntrackEntriesUsed
    expr: (node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.75
    labels:
      severity: warning
    annotations:
      description: of {{ $labels.exported_instance }} conntrack entries are used {{ printf "%.0f" $value }} .
      summary: Number of conntrack are getting close to the limit.
  #12 Node Exporter не смог очистить цель. (ScrapeError)
  - alert: NodeTextFileCollectorScrapeError 
    expr: node_textfile_scrape_error{job="node-exporter"} == 1
    labels:
      severity: warning
    annotations:
      description: Node Exporter  {{ $labels.exported_instance }} text file collector failed to scrape.
      summary: Node Exporter text file collector failed to scrape.
  #13 Неправильное время на ноде
  - alert: NodeClockSkewDetected
    expr: (node_timex_offset_seconds{job="node-exporter"} > 0.05 and deriv(node_timex_offset_seconds{job="node-exporter"}[5m]) >= 0) or (node_timex_offset_seconds{job="node-exporter"} < -0.05 and deriv(node_timex_offset_seconds{job="node-exporter"}[5m]) <= 0)
    for: 10m
    labels:
      severity: warning
    annotations:
      description: Clock on {{ $labels.exported_instance }} is out of sync by more than 300s. Ensure NTP is configured correctly on this host.
      summary: Clock skew detected.
  #14 Часы на ноде не синхранизируются
  - alert: NodeClockNotSynchronising
    expr: min_over_time(node_timex_sync_status{job="node-exporter"}[5m]) == 0 and node_timex_maxerror_seconds{job="node-exporter"} >= 16
    for: 10m
    labels:
      severity: warning
    annotations:
      description: Clock on {{ $labels.exported_instance }} is not synchronising. Ensure NTP is configured on this host.
      summary: Clock not synchronising.
  #15 Деградировал RAID на ноде
  - alert: NodeRAIDDegraded
    expr: node_md_disks_required{device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)",job="node-exporter"} - ignoring (state) (node_md_disks{device=~"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)",job="node-exporter",state="active"}) > 0
    for: 15m
    labels:
      severity: critical
    annotations:
      description: RAID array '{{ $labels.device }}' on {{ $labels.exported_instance }} is in degraded state due to one or more disks failures. Number of spare drives is insufficient to fix issue automatically.
      summary: RAID Array is degraded
  
  #16 На ноде заканчиваются доступные дескрипторы файлов занято больше 90%
  - alert: NodeFileDescriptorLimit
    expr: (node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 90)
    for: 15m
    labels:
      severity: critical
    annotations:
      description: File descriptors limit at {{ $labels.instance }} is currently at {{ printf "%.2f" $value }}%.
      summary: Kernel is predicted to exhaust file descriptors limit soon.