groups:
- name: Rabbitmq_rules
  rules:
  # 1. В кластере  RabbitMQ изменилось количество узлов.
  - alert: RabbitmqNodeDown
    expr: rate(count by(job,statefulset_kubernetes_io_pod_name) (rabbitmq_build_info)[1m]) > 0
    for: 1m
    labels:
        severity: critical
    annotations:
        summary: "Узел Rabbitmq не работает."
        description: "В кластере \n {{ $labels.job }} не доступен узел \n {{ $labels.statefulset_kubernetes_io_pod_name }} ."

  #2. Узел использует более 90% выделенной оперативной памяти
  - alert: RabbitmqMemoryHigh
    expr: rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes * 100 > 0.9
    for: 2m
    labels:
        severity: warning
    annotations:
        summary: "Высокий уровень потребляемой памяти Rabbitmq." 
        description: "В кластере \n {{ $labels.job }}, узел \n {{ $labels.statefulset_kubernetes_io_pod_name}} использует более 90% выделенной оперативной памяти"

  #3. Узел использует более 90% файловых дескрипторов.
  - alert: RabbitmqFileDescriptorsUsage
    expr: rabbitmq_process_open_fds / rabbitmq_process_max_fds * 10000 > 0.9
    labels:
        severity: warning
    annotations:
        summary: "Высокий уровень потребляемой файловых дескрипторов Rabbitmq"
        description: "В кластере \n {{ $labels.job }}, узел \n {{ $labels.statefulset_kubernetes_io_pod_name }} использует более 90% файловых дескрипторов"

  #4. переполнение очереди. Метрика показывает сколько сообщений не отправлено получателю.
  - alert: RabbitmqTooManyMessagesInQueue
    expr: sum by(datacenter,job,queue) (rabbitmq_queue_messages_ready) > 60
    for: 10m
    labels:
        severity: warning
    annotations:
        summary: "Много необработанных сообщений в очереди "
        description: "В кластере \n {{ $labels.job }}, в очереди \n {{ $labels.queue }} необработанных сообщений = {{ $value }}"

  #5. Слишком мало конектов к ноде кластера
  - alert: RabbitmqLOWConnections
    expr: sum by(datacenter,job) (rabbitmq_connections) < 1
    for: 15m
    labels:
        severity: warning
    annotations:
        summary: "Нет коннектов к кластеру."
        description: "Ни одного подключения к {{ $labels.job }} в течении 15мин"

