---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-minion
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/location-snippets: |
        access_log  syslog:server=graylog.intsite.org:12222,facility=local7,severity=info,tag=grafana main;
        if ($zone_go) {
            return 403;
        }
        proxy_pass_request_headers on;
        proxy_redirect            off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ .Values.grafanaDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serviceName }}
            port:
               number: {{ .Values.network.port }}
---