apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-pv-creator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/gen7777/HomeCluster'
    path: ArgoCD_app_system/01-clusterapp/01-nfs
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs-client
  syncPolicy:
    syncOptions:
      - CreateNamespace=true