apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubesystem-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/gen7777/HomeCluster'
    path: ArgoCD_app_system/01-clusterapp/02-kube-system-ns
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy: { }