apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/gen7777/HomeCluster'
    path: ArgoCD_app_system/01-clusterapp/03-ingress-nginx
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true