apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}
data:
    alertmanager.yml:
{{ toYaml .Values.amConfig | quote | indent 6}}

{{ (.Files.Glob (print  "config/*.tmpl"  ) ).AsConfig | indent 4 }}



