---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  ports:
    - port: {{ .Values.network.port }}
      protocol: TCP
      targetPort: {{ .Values.network.name }}
  selector:
    app: {{ .Values.serviceName }}
  sessionAffinity: None

---
