serviceName: node-exporter
image:
  repository: nexus.intsite.org/nodeexporter-1.5.0
  tag: 222
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9101
  targetPort: 9101
  nodePort:
  listenOnAllInterfaces: true
  annotations:
    prometheus.io/scrape: "true"
prometheus:
  monitor:
    enabled: false
    additionalLabels: {}
    namespace: ""
    relabelings: []
    scrapeTimeout: 10s
## Customize the updateStrategy if set
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
resources: {}
hostNetwork: true
affinity: {}
podAnnotations: {}
podLabels: {}
nodeSelector: {}
tolerations:
  - effect: NoSchedule
    operator: Exists
extraArgs: []
extraHostVolumeMounts: []
configmaps: []
namespaceOverride: ""
sidecars: []
sidecarVolumeMount: []
