serviceName: alertmanager-hq
alertmanagerDomain: alertmanager-hq.intsite.org

image:
    name: nexus.intsite.org/alertmanager-0.25.0
    tag:  240

network:
    port: 9093

amConfig:
    global:
        resolve_timeout: 5m
    route:
        receiver: 'telegram_hq'
        group_by:
            - datacenter
            - severity
            - namespace            
        routes:
        - receiver: 'telegram_hq' 
          match:
            datacenter: hq
          repeat_interval: 24h
          continue: true

        - receiver: 'null'  
          match:
            datacenter: datapro
          repeat_interval: 24h
          continue: true
        
        - receiver: 'null'  
          match:
            datacenter: dp1
          repeat_interval: 24h
          continue: true
                 
        - receiver: 'null'  
          match:
            alertname: Watchdog
          repeat_interval: 24h
          continue: true
          
        - receiver: 'null'
          match:
            alertname: KubeVersionMismatch
          repeat_interval: 24h
          continue: true
          
        - receiver: "null"
          match:
            alertname: InfoInhibitor
          repeat_interval: 24h
          continue: true

        - receiver: "null"
          match:
            alertname: CPUThrottlingHigh
          repeat_interval: 24h
          continue: true

    receivers:
        - name: 'null'
        - name: 'telegram_hq'
          telegram_configs:
           - api_url: https://api.telegram.org
             send_resolved: true
             bot_token: 5765938425:AAGu0OYns37vKyuFvC2vBFD0EFpU8BDhSkk
             chat_id: -1001824167949
             message:  '{{ template "telegram.message" .}}'
             parse_mode: 'HTML'

    templates:
        - /etc/alertmanager/*.tmpl
